In [1]:
# import urllib library
from urllib.request import urlopen
  
# import json
import json

# store the URL in url as 
# parameter for urlopen
url = "https://data.cityofnewyork.us/resource/erm2-nwe9.json?$query=SELECT%0A%20%20%60unique_key%60%2C%0A%20%20%60created_date%60%2C%0A%20%20%60closed_date%60%2C%0A%20%20%60agency%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60complaint_type%60%2C%0A%20%20%60descriptor%60%2C%0A%20%20%60location_type%60%2C%0A%20%20%60incident_zip%60%2C%0A%20%20%60status%60%2C%0A%20%20%60community_board%60%2C%0A%20%20%60borough%60%2C%0A%20%20%60open_data_channel_type%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60%3A%40computed_region_92fq_4b7q%60%2C%0A%20%20%60%3A%40computed_region_sbqj_enih%60%0AWHERE%0A%20%20(%60created_date%60%0A%20%20%20%20%20BETWEEN%20%222022-01-01T00%3A00%3A00%22%20%3A%3A%20floating_timestamp%0A%20%20%20%20%20AND%20%222023-07-05T22%3A22%3A17%22%20%3A%3A%20floating_timestamp)%0A%20%20AND%20((%60closed_date%60%20IS%20NOT%20NULL)%20AND%20caseless_eq(%60status%60%2C%20%22Closed%22))%0AORDER%20BY%20%60created_date%60%20DESC%20NULL%20FIRST"
  
# store the response of URL
response = urlopen(url)
  
# storing the JSON response 
# from url in data
data_json = json.loads(response.read())

In [ ]:
# importing libraries needed for data analysis
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
# outputs JSON results
print(data_json)

[{'unique_key': '58116814', 'created_date': '2023-07-05T22:22:03.000', 'closed_date': '2023-08-09T00:00:00.000', 'agency': 'DOB', 'agency_name': 'Department of Buildings', 'complaint_type': 'General Construction/Plumbing', 'descriptor': 'Building Permit - None', 'incident_zip': '10312', 'status': 'Closed', 'community_board': '03 STATEN ISLAND', 'borough': 'STATEN ISLAND', 'open_data_channel_type': 'UNKNOWN', 'latitude': '40.53648118922242', 'longitude': '-74.15657605064793', ':@computed_region_92fq_4b7q': '9', ':@computed_region_sbqj_enih': '76'}, {'unique_key': '58112935', 'created_date': '2023-07-05T22:22:03.000', 'closed_date': '2023-08-03T00:00:00.000', 'agency': 'DOB', 'agency_name': 'Department of Buildings', 'complaint_type': 'Elevator', 'descriptor': 'Elevator - Single Device On Property/No Alternate Service', 'incident_zip': '10459', 'status': 'Closed', 'community_board': '02 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'UNKNOWN', 'latitude': '40.82319312657684', 'longitude': '-73.88927925606889', ':@computed_region_92fq_4b7q': '43', ':@computed_region_sbqj_enih': '24'}, {'unique_key': '58102542', 'created_date': '2023-07-05T22:21:45.000', 'closed_date': '2023-07-05T22:38:37.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Fireworks', 'descriptor': 'N/A', 'location_type': 'Residential Building/House', 'incident_zip': '11213', 'status': 'Closed', 'community_board': '09 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.664271427215475', 'longitude': '-73.93059495473237', ':@computed_region_92fq_4b7q': '17', ':@computed_region_sbqj_enih': '44'}, {'unique_key': '58101494', 'created_date': '2023-07-05T22:21:41.000', 'closed_date': '2023-07-05T22:50:13.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Blocked Driveway', 'descriptor': 'No Access', 'location_type': 'Street/Sidewalk', 'incident_zip': '11369', 'status': 'Closed', 'community_board': '03 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'PHONE', 'latitude': '40.75865400041392', 'longitude': '-73.876305234797', ':@computed_region_92fq_4b7q': '21', ':@computed_region_sbqj_enih': '73'}, {'unique_key': '58104528', 'created_date': '2023-07-05T22:21:38.000', 'closed_date': '2023-07-05T22:50:01.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Residential', 'descriptor': 'Loud Music/Party', 'location_type': 'Residential Building/House', 'incident_zip': '10302', 'status': 'Closed', 'community_board': '01 STATEN ISLAND', 'borough': 'STATEN ISLAND', 'open_data_channel_type': 'ONLINE', 'latitude': '40.63333427323517', 'longitude': '-74.13502403610045', ':@computed_region_92fq_4b7q': '13', ':@computed_region_sbqj_enih': '75'}, {'unique_key': '58105506', 'created_date': '2023-07-05T22:21:34.000', 'closed_date': '2023-07-06T00:32:37.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Fireworks', 'descriptor': 'N/A', 'location_type': 'Street/Sidewalk', 'incident_zip': '10310', 'status': 'Closed', 'community_board': '01 STATEN ISLAND', 'borough': 'STATEN ISLAND', 'open_data_channel_type': 'ONLINE', 'latitude': '40.63776682754764', 'longitude': '-74.11509349235297', ':@computed_region_92fq_4b7q': '13', ':@computed_region_sbqj_enih': '74'}, {'unique_key': '58104527', 'created_date': '2023-07-05T22:21:12.000', 'closed_date': '2023-07-05T22:55:11.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Residential', 'descriptor': 'Loud Music/Party', 'location_type': 'Residential Building/House', 'incident_zip': '11211', 'status': 'Closed', 'community_board': '01 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.71888381029733', 'longitude': '-73.95142536226368', ':@computed_region_92fq_4b7q': '38', ':@computed_region_sbqj_enih': '57'}, {'unique_key': '58103805', 'created_date': '2023-07-05T22:21:02.000', 'closed_date': '2023-07-05T23:14:51.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Blocked Driveway', 'descriptor': 'Partial Access', 'location_type': 'Street/Sidewalk', 'incident_zip': '11210', 'status': 'Closed', 'community_board': '14 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.61691917007343', 'longitude': '-73.94765626630915', ':@computed_region_92fq_4b7q': '26', ':@computed_region_sbqj_enih': '43'}, {'unique_key': '58108576', 'created_date': '2023-07-05T22:21:02.000', 'closed_date': '2023-07-05T22:59:13.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Parking', 'descriptor': 'Blocked Hydrant', 'location_type': 'Street/Sidewalk', 'incident_zip': '10467', 'status': 'Closed', 'community_board': '07 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'MOBILE', 'latitude': '40.882211991020355', 'longitude': '-73.88317784449366', ':@computed_region_92fq_4b7q': '40', ':@computed_region_sbqj_enih': '34'}, {'unique_key': '58104251', 'created_date': '2023-07-05T22:21:02.000', 'closed_date': '2023-07-05T22:23:20.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Residential', 'descriptor': 'Banging/Pounding', 'location_type': 'Residential Building/House', 'incident_zip': '11209', 'status': 'Closed', 'community_board': '10 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.61814816576145', 'longitude': '-74.03164022879972', ':@computed_region_92fq_4b7q': '44', ':@computed_region_sbqj_enih': '41'}, {'unique_key': '58102938', 'created_date': '2023-07-05T22:20:58.000', 'closed_date': '2023-07-06T04:29:16.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Blocked Driveway', 'descriptor': 'Partial Access', 'location_type': 'Street/Sidewalk', 'incident_zip': '11414', 'status': 'Closed', 'community_board': '10 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'PHONE', 'latitude': '40.66177353335338', 'longitude': '-73.85416289879332', ':@computed_region_92fq_4b7q': '41', ':@computed_region_sbqj_enih': '64'}, {'unique_key': '58104019', 'created_date': '2023-07-05T22:20:55.000', 'closed_date': '2023-07-05T23:15:10.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Blocked Driveway', 'descriptor': 'No Access', 'location_type': 'Street/Sidewalk', 'incident_zip': '10467', 'status': 'Closed', 'community_board': '12 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'PHONE', 'latitude': '40.88387828880427', 'longitude': '-73.86112192275972', ':@computed_region_92fq_4b7q': '2', ':@computed_region_sbqj_enih': '30'}, {'unique_key': '58106923', 'created_date': '2023-07-05T22:20:49.000', 'closed_date': '2023-07-05T22:39:15.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Fireworks', 'descriptor': 'N/A', 'location_type': 'Street/Sidewalk', 'incident_zip': '11223', 'status': 'Closed', 'community_board': '11 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.60632266148869', 'longitude': '-73.9758310607478', ':@computed_region_92fq_4b7q': '18', ':@computed_region_sbqj_enih': '37'}, {'unique_key': '58101469', 'created_date': '2023-07-05T22:20:34.000', 'closed_date': '2023-07-05T22:51:01.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Residential', 'descriptor': 'Loud Music/Party', 'location_type': 'Residential Building/House', 'incident_zip': '10469', 'status': 'Closed', 'community_board': '11 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'ONLINE', 'latitude': '40.868271431063526', 'longitude': '-73.85187331611881', ':@computed_region_92fq_4b7q': '2', ':@computed_region_sbqj_enih': '32'}, {'unique_key': '58107531', 'created_date': '2023-07-05T22:20:30.000', 'closed_date': '2023-07-05T22:37:21.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Street/Sidewalk', 'descriptor': 'Loud Music/Party', 'location_type': 'Street/Sidewalk', 'incident_zip': '10027', 'status': 'Closed', 'community_board': '10 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'MOBILE', 'latitude': '40.80757450971996', 'longitude': '-73.95103191888202', ':@computed_region_92fq_4b7q': '36', ':@computed_region_sbqj_enih': '18'}, {'unique_key': '58101769', 'created_date': '2023-07-05T22:20:24.000', 'closed_date': '2023-07-05T22:30:13.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Non-Emergency Police Matter', 'descriptor': 'Other (complaint details)', 'location_type': 'Street/Sidewalk', 'incident_zip': '11375', 'status': 'Closed', 'community_board': '06 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'ONLINE', 'latitude': '40.72436527800172', 'longitude': '-73.8541269456186', ':@computed_region_92fq_4b7q': '28', ':@computed_region_sbqj_enih': '70'}, {'unique_key': '58103364', 'created_date': '2023-07-05T22:20:19.000', 'closed_date': '2023-07-05T22:48:27.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Parking', 'descriptor': 'Commercial Overnight Parking', 'location_type': 'Street/Sidewalk', 'incident_zip': '10021', 'status': 'Closed', 'community_board': '08 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'MOBILE', 'latitude': '40.770214508708676', 'longitude': '-73.9616915898386', ':@computed_region_92fq_4b7q': '51', ':@computed_region_sbqj_enih': '11'}, {'unique_key': '58104480', 'created_date': '2023-07-05T22:20:07.000', 'closed_date': '2023-07-06T03:59:27.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Parking', 'descriptor': 'Posted Parking Sign Violation', 'location_type': 'Street/Sidewalk', 'incident_zip': '11414', 'status': 'Closed', 'community_board': '10 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'MOBILE', 'latitude': '40.64954369180796', 'longitude': '-73.83456011255521', ':@computed_region_92fq_4b7q': '41', ':@computed_region_sbqj_enih': '64'}, {'unique_key': '58104642', 'created_date': '2023-07-05T22:20:03.000', 'closed_date': '2023-07-05T22:34:17.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Fireworks', 'descriptor': 'N/A', 'location_type': 'Street/Sidewalk', 'incident_zip': '10027', 'status': 'Closed', 'community_board': '09 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.81611059905848', 'longitude': '-73.95799823511656', ':@computed_region_92fq_4b7q': '23', ':@computed_region_sbqj_enih': '17'}, {'unique_key': '58117014', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-06T09:29:00.000', 'agency': 'DEP', 'agency_name': 'Department of Environmental Protection', 'complaint_type': 'Lead', 'descriptor': 'Lead Kit Request (Residential) (L10)', 'incident_zip': '10280', 'status': 'Closed', 'community_board': '01 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.70811402884461', 'longitude': '-74.017630483332', ':@computed_region_92fq_4b7q': '32', ':@computed_region_sbqj_enih': '1'}, {'unique_key': '58121385', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-07T10:33:00.000', 'agency': 'DEP', 'agency_name': 'Department of Environmental Protection', 'complaint_type': 'Water System', 'descriptor': 'Hydrant Running Full (WA4)', 'incident_zip': '10452', 'status': 'Closed', 'community_board': '04 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'ONLINE', 'latitude': '40.841752298115495', 'longitude': '-73.9143883173933', ':@computed_region_92fq_4b7q': '29', ':@computed_region_sbqj_enih': '27'}, {'unique_key': '58121315', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-06T08:51:00.000', 'agency': 'DEP', 'agency_name': 'Department of Environmental Protection', 'complaint_type': 'Noise', 'descriptor': 'Noise, Barking Dog (NR5)', 'incident_zip': '11208', 'status': 'Closed', 'community_board': '05 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.68773380465783', 'longitude': '-73.8728021572523', ':@computed_region_92fq_4b7q': '37', ':@computed_region_sbqj_enih': '47'}, {'unique_key': '58117034', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-05T22:20:00.000', 'agency': 'DEP', 'agency_name': 'Department of Environmental Protection', 'complaint_type': 'Water System', 'descriptor': 'Hydrant Running Full (WA4)', 'incident_zip': '11207', 'status': 'Closed', 'community_board': '04 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.688931453698274', 'longitude': '-73.90504343933692', ':@computed_region_92fq_4b7q': '37', ':@computed_region_sbqj_enih': '53'}, {'unique_key': '58123160', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-05T22:20:00.000', 'agency': 'DEP', 'agency_name': 'Department of Environmental Protection', 'complaint_type': 'Water System', 'descriptor': 'Hydrant Running Full (WA4)', 'incident_zip': '10040', 'status': 'Closed', 'community_board': '12 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'PHONE', 'latitude': '40.85482728192759', 'longitude': '-73.92943094675587', ':@computed_region_92fq_4b7q': '39', ':@computed_region_sbqj_enih': '22'}, {'unique_key': '58114013', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-06T00:30:00.000', 'agency': 'DEP', 'agency_name': 'Department of Environmental Protection', 'complaint_type': 'Water System', 'descriptor': 'Hydrant Running Full (WA4)', 'incident_zip': '10029', 'status': 'Closed', 'community_board': '11 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.79125760216967', 'longitude': '-73.94600241145547', ':@computed_region_92fq_4b7q': '35', ':@computed_region_sbqj_enih': '14'}, {'unique_key': '58110905', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-07T12:54:41.000', 'agency': 'DPR', 'agency_name': 'Department of Parks and Recreation', 'complaint_type': 'Maintenance or Facility', 'descriptor': 'Unsecured Facility', 'location_type': 'Park', 'incident_zip': '10458', 'status': 'Closed', 'community_board': '07 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'UNKNOWN', 'latitude': '40.86525838276163', 'longitude': '-73.8949866557406', ':@computed_region_92fq_4b7q': '22', ':@computed_region_sbqj_enih': '34'}, {'unique_key': '58122944', 'created_date': '2023-07-05T22:20:00.000', 'closed_date': '2023-07-09T11:15:00.000', 'agency': 'DEP', 'agency_name': 'Department of Environmental Protection', 'complaint_type': 'Water System', 'descriptor': 'Hydrant Running Full (WA4)', 'incident_zip': '10462', 'status': 'Closed', 'community_board': '11 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'PHONE'}, {'unique_key': '58109033', 'created_date': '2023-07-05T22:19:44.000', 'closed_date': '2023-07-05T22:59:32.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Blocked Driveway', 'descriptor': 'Partial Access', 'location_type': 'Street/Sidewalk', 'incident_zip': '10459', 'status': 'Closed', 'community_board': '02 BRONX', 'borough': 'BRONX', 'open_data_channel_type': 'PHONE', 'latitude': '40.82438833690627', 'longitude': '-73.8996507535539', ':@computed_region_92fq_4b7q': '43', ':@computed_region_sbqj_enih': '24'}, {'unique_key': '58109892', 'created_date': '2023-07-05T22:19:30.000', 'closed_date': '2023-07-06T03:35:50.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Abandoned Vehicle', 'descriptor': 'With License Plate', 'location_type': 'Street/Sidewalk', 'incident_zip': '11414', 'status': 'Closed', 'community_board': '10 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'PHONE', 'latitude': '40.66177353335338', 'longitude': '-73.85416289879332', ':@computed_region_92fq_4b7q': '41', ':@computed_region_sbqj_enih': '64'}, {'unique_key': '58103932', 'created_date': '2023-07-05T22:19:16.000', 'closed_date': '2023-07-06T01:51:38.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Parking', 'descriptor': 'Blocked Crosswalk', 'location_type': 'Street/Sidewalk', 'incident_zip': '11364', 'status': 'Closed', 'community_board': '11 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'MOBILE', 'latitude': '40.74165484248502', 'longitude': '-73.76075326891123', ':@computed_region_92fq_4b7q': '16', ':@computed_region_sbqj_enih': '69'}, {'unique_key': '58105618', 'created_date': '2023-07-05T22:19:11.000', 'closed_date': '2023-07-05T22:40:36.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Illegal Fireworks', 'descriptor': 'N/A', 'location_type': 'Store/Commercial', 'incident_zip': '11222', 'status': 'Closed', 'community_board': '01 BROOKLYN', 'borough': 'BROOKLYN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.73026721203961', 'longitude': '-73.95358552689403', ':@computed_region_92fq_4b7q': '38', ':@computed_region_sbqj_enih': '57'}, {'unique_key': '58108910', 'created_date': '2023-07-05T22:19:09.000', 'closed_date': '2023-08-01T09:06:41.000', 'agency': 'HPD', 'agency_name': 'Department of Housing Preservation and Development', 'complaint_type': 'ELECTRIC', 'descriptor': 'NO LIGHTING', 'location_type': 'RESIDENTIAL BUILDING', 'incident_zip': '11373', 'status': 'Closed', 'community_board': '04 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'PHONE', 'latitude': '40.74203799388003', 'longitude': '-73.88493568939737', ':@computed_region_92fq_4b7q': '5', ':@computed_region_sbqj_enih': '68'}, {'unique_key': '58108569', 'created_date': '2023-07-05T22:19:00.000', 'closed_date': '2023-07-05T22:56:35.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Vehicle', 'descriptor': 'Car/Truck Music', 'location_type': 'Street/Sidewalk', 'incident_zip': '10025', 'status': 'Closed', 'community_board': '07 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'MOBILE', 'latitude': '40.79639756165641', 'longitude': '-73.96493425316099', ':@computed_region_92fq_4b7q': '23', ':@computed_region_sbqj_enih': '15'}, {'unique_key': '58110179', 'created_date': '2023-07-05T22:18:59.000', 'closed_date': '2023-07-05T23:14:06.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Street/Sidewalk', 'descriptor': 'Loud Music/Party', 'location_type': 'Street/Sidewalk', 'incident_zip': '10027', 'status': 'Closed', 'community_board': '09 MANHATTAN', 'borough': 'MANHATTAN', 'open_data_channel_type': 'ONLINE', 'latitude': '40.81783539703247', 'longitude': '-73.95373761025542', ':@computed_region_92fq_4b7q': '23', ':@computed_region_sbqj_enih': '19'}, {'unique_key': '58101431', 'created_date': '2023-07-05T22:18:57.000', 'closed_date': '2023-07-05T22:38:49.000', 'agency': 'NYPD', 'agency_name': 'New York City Police Department', 'complaint_type': 'Noise - Street/Sidewalk', 'descriptor': 'Loud Music/Party', 'location_type': 'Street/Sidewalk', 'incident_zip': '11435', 'status': 'Closed', 'community_board': '12 QUEENS', 'borough': 'QUEENS', 'open_data_channel_type': 'MOBILE', 'latitude': '40.70348111753405', 'longitude': '-73.8062655497942', ':@computed_region_92fq_4b7q': '24', ':@computed_region_sbqj_enih': '61'}, {'unique_key': '58110371', 'created_date': '2023-07-05T22:18:48.000', 'closed_date': '2023-07-06T11:21:15.000', 'agency': 'HPD', 'agency_name': 'Department of Housing Preservation and Development', 'complaint_type': 'HEAT/HOT WATER', 'descriptor': 'ENTIRE BUILDING', 'location_type': 'RESIDENTIAL BUILDING', 'incident_zip': '10462', 'status': 'Closed', 'community_board': '09 BRONX', 'borough': 'BRONX', 'open_data_channel_type'

In [4]:
# JSON results converted into dataframe
df = pd.json_normalize(data_json)

In [5]:
# information regarding dataframe -- columns, datatypes, etc.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   unique_key                   1000 non-null   object
 1   created_date                 1000 non-null   object
 2   closed_date                  1000 non-null   object
 3   agency                       1000 non-null   object
 4   agency_name                  1000 non-null   object
 5   complaint_type               1000 non-null   object
 6   descriptor                   1000 non-null   object
 7   incident_zip                 997 non-null    object
 8   status                       1000 non-null   object
 9   community_board              1000 non-null   object
 10  borough                      1000 non-null   object
 11  open_data_channel_type       1000 non-null   object
 12  latitude                     988 non-null    object
 13  longitude                    988 non-null    object
 14  :@computed_region_92fq_4b7q  988 non-null    object
 15  :@computed_region_sbqj_enih  988 non-null    object
 16  location_type                867 non-null    object
dtypes: object(17)
memory usage: 132.9+ KB

In [6]:
# outputs first 10 rows of dataframe
df.head(10)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location_type
0,58116814,2023-07-05T22:22:03.000,2023-08-09T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,UNKNOWN,40.53648118922242,-74.15657605064793,9,76,NaN
1,58112935,2023-07-05T22:22:03.000,2023-08-03T00:00:00.000,DOB,Department of Buildings,Elevator,Elevator - Single Device On Property/No Altern...,10459,Closed,02 BRONX,BRONX,UNKNOWN,40.82319312657684,-73.88927925606889,43,24,NaN
2,58102542,2023-07-05T22:21:45.000,2023-07-05T22:38:37.000,NYPD,New York City Police Department,Illegal Fireworks,N/A,11213,Closed,09 BROOKLYN,BROOKLYN,ONLINE,40.664271427215475,-73.93059495473237,17,44,Residential Building/House
3,58101494,2023-07-05T22:21:41.000,2023-07-05T22:50:13.000,NYPD,New York City Police Department,Blocked Driveway,No Access,11369,Closed,03 QUEENS,QUEENS,PHONE,40.75865400041392,-73.876305234797,21,73,Street/Sidewalk
4,58104528,2023-07-05T22:21:38.000,2023-07-05T22:50:01.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,10302,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63333427323517,-74.13502403610045,13,75,Residential Building/House
5,58105506,2023-07-05T22:21:34.000,2023-07-06T00:32:37.000,NYPD,New York City Police Department,Illegal Fireworks,N/A,10310,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63776682754764,-74.11509349235297,13,74,Street/Sidewalk
6,58104527,2023-07-05T22:21:12.000,2023-07-05T22:55:11.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.71888381029733,-73.95142536226368,38,57,Residential Building/House
7,58103805,2023-07-05T22:21:02.000,2023-07-05T23:14:51.000,NYPD,New York City Police Department,Blocked Driveway,Partial Access,11210,Closed,14 BROOKLYN,BROOKLYN,ONLINE,40.61691917007343,-73.94765626630915,26,43,Street/Sidewalk
8,58108576,2023-07-05T22:21:02.000,2023-07-05T22:59:13.000,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,10467,Closed,07 BRONX,BRONX,MOBILE,40.882211991020355,-73.88317784449366,40,34,Street/Sidewalk
9,58104251,2023-07-05T22:21:02.000,2023-07-05T22:23:20.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,11209,Closed,10 BROOKLYN,BROOKLYN,ONLINE,40.61814816576145,-74.03164022879972,44,41,Residential Building/House

In [8]:
# outputs last 10 rows of dataframe
df.tail(10)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location_type
990,58103781,2023-07-05T20:22:33.000,2023-07-05T20:25:45.000,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,11228,Closed,10 BROOKLYN,BROOKLYN,ONLINE,40.61766136207577,-74.0243783589393,44,41,Street/Sidewalk
991,58109814,2023-07-05T20:22:13.000,2023-07-06T01:58:29.000,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Music,10451,Closed,04 BRONX,BRONX,MOBILE,40.823069720490786,-73.92739430604901,35,27,Street/Sidewalk
992,58110551,2023-07-05T20:22:09.000,2023-07-05T20:45:23.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11433,Closed,12 QUEENS,QUEENS,ONLINE,40.695972973618375,-73.79450216305685,46,61,Residential Building/House
993,58104504,2023-07-05T20:21:26.000,2023-07-16T11:00:39.000,HPD,Department of Housing Preservation and Develop...,UNSANITARY CONDITION,PESTS,11416,Closed,09 QUEENS,QUEENS,ONLINE,40.68625315151093,-73.85549395422537,41,60,RESIDENTIAL BUILDING
994,58105297,2023-07-05T20:21:21.000,2023-07-07T18:29:42.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.70924127809079,-73.95792851029476,30,56,RESIDENTIAL BUILDING
995,58107939,2023-07-05T20:21:00.000,2023-07-06T02:25:00.000,DOT,Department of Transportation,Traffic Signal Condition,Veh Signal Lamp,11213,Closed,08 BROOKLYN,BROOKLYN,UNKNOWN,40.67325789139592,-73.93069735829563,49,49,NaN
996,58106580,2023-07-05T20:21:00.000,2023-07-07T09:50:00.000,DOT,Department of Transportation,Traffic Signal Condition,Controller,11373,Closed,04 QUEENS,QUEENS,UNKNOWN,40.73888938191339,-73.86676119844235,5,68,NaN
997,58108553,2023-07-05T20:20:51.000,2023-07-05T21:59:22.000,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Music,10468,Closed,08 BRONX,BRONX,ONLINE,40.8732751835183,-73.90066896231632,29,33,Street/Sidewalk
998,58105417,2023-07-05T20:20:34.000,2023-07-05T20:20:34.000,DOHMH,Department of Health and Mental Hygiene,Standing Water,Swimming Pool - Unmaintained,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,ONLINE,40.54832297298355,-74.1856166697432,9,77,1-2 Family Dwelling
999,58104686,2023-07-05T20:20:13.000,2023-07-05T22:01:25.000,NYPD,New York City Police Department,Illegal Parking,Double Parked Blocking Traffic,11207,Closed,05 BROOKLYN,BROOKLYN,MOBILE,40.68333356310445,-73.8941193737894,37,47,Street/Sidewalk

In [9]:
# dropping columns that are not needed
df = df.drop(columns=[':@computed_region_92fq_4b7q',':@computed_region_sbqj_enih'])

In [10]:
# outputs rows with null zip code values (incident_zip)
df[df['incident_zip'].isnull()]

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type
123,58106368,2023-07-05T22:10:00.000,2023-07-06T03:55:00.000,DOT,Department of Transportation,Traffic Signal Condition,Underground,NaN,Closed,Unspecified MANHATTAN,MANHATTAN,UNKNOWN,NaN,NaN,NaN
306,58106252,2023-07-05T21:49:44.000,2023-07-05T23:02:28.000,NYPD,New York City Police Department,Panhandling,N/A,NaN,Closed,Unspecified QUEENS,QUEENS,MOBILE,40.75687886664907,-73.92074189506906,Subway
617,58111334,2023-07-05T21:18:06.000,2023-07-05T23:15:24.000,NYPD,New York City Police Department,Panhandling,N/A,NaN,Closed,Unspecified MANHATTAN,MANHATTAN,MOBILE,40.79480578014678,-73.94440682287397,Subway

In [12]:
# Using the latitudinal and logitudinal coordinates of two records with null zip code values,
# was able to find the zip codes through a Google Maps search
# Replacing the null zip code values with the correct zip codes
df['incident_zip'][305] = '11103'
df['incident_zip'][614] = '10029'

In [13]:
# Only including records with non-null zip code values
# Then reset the index number
df = df[pd.notnull(df['incident_zip'])]
df = df.reset_index(drop=True)

In [14]:
# Outputs rows with null location type values
df[df['location_type'].isnull()]

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type
0,58116814,2023-07-05T22:22:03.000,2023-08-09T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,UNKNOWN,40.53648118922242,-74.15657605064793,NaN
1,58112935,2023-07-05T22:22:03.000,2023-08-03T00:00:00.000,DOB,Department of Buildings,Elevator,Elevator - Single Device On Property/No Altern...,10459,Closed,02 BRONX,BRONX,UNKNOWN,40.82319312657684,-73.88927925606889,NaN
19,58117014,2023-07-05T22:20:00.000,2023-07-06T09:29:00.000,DEP,Department of Environmental Protection,Lead,Lead Kit Request (Residential) (L10),10280,Closed,01 MANHATTAN,MANHATTAN,ONLINE,40.70811402884461,-74.017630483332,NaN
20,58121385,2023-07-05T22:20:00.000,2023-07-07T10:33:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,ONLINE,40.841752298115495,-73.9143883173933,NaN
21,58121315,2023-07-05T22:20:00.000,2023-07-06T08:51:00.000,DEP,Department of Environmental Protection,Noise,"Noise, Barking Dog (NR5)",11208,Closed,05 BROOKLYN,BROOKLYN,ONLINE,40.68773380465783,-73.8728021572523,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,58122411,2023-07-05T20:23:36.000,2023-08-23T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Debris - Excessive,11211,Closed,01 BROOKLYN,BROOKLYN,UNKNOWN,40.71463773373357,-73.93993577498533,NaN
981,58117016,2023-07-05T20:23:00.000,2023-07-06T20:45:00.000,DEP,Department of Environmental Protection,Noise,Noise: Alarms (NR3),11230,Closed,14 BROOKLYN,BROOKLYN,PHONE,40.63298747798288,-73.97212850230288,NaN
982,58114066,2023-07-05T20:23:00.000,2023-07-05T21:00:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11220,Closed,07 BROOKLYN,BROOKLYN,PHONE,40.643425901464816,-74.01206416378167,NaN
992,58107939,2023-07-05T20:21:00.000,2023-07-06T02:25:00.000,DOT,Department of Transportation,Traffic Signal Condition,Veh Signal Lamp,11213,Closed,08 BROOKLYN,BROOKLYN,UNKNOWN,40.67325789139592,-73.93069735829563,NaN
993,58106580,2023-07-05T20:21:00.000,2023-07-07T09:50:00.000,DOT,Department of Transportation,Traffic Signal Condition,Controller,11373,Closed,04 QUEENS,QUEENS,UNKNOWN,40.73888938191339,-73.86676119844235,NaN

In [15]:
# For rows with null location type values, outputs unique complaint type values
df[df['location_type'].isnull()]['complaint_type'].unique()

array(['General Construction/Plumbing', 'Elevator', 'Lead',
       'Water System', 'Noise', 'Traffic Signal Condition', 'Air Quality',
       'Water Conservation', 'Street Light Condition', 'Street Condition',
       'Sewer', 'Emergency Response Team (ERT)', 'Hazardous Materials',
       'Building/Use', 'AHV Inspection Unit'], dtype=object)

In [16]:
# For rows with null location type values, outputs unique complaint type values and number of associated rows
df[df['location_type'].isnull()]['complaint_type'].value_counts()

Water System                     57
Air Quality                      18
Traffic Signal Condition         16
Street Light Condition            9
General Construction/Plumbing     8
Noise                             7
Elevator                          3
Water Conservation                3
Street Condition                  3
Sewer                             3
Lead                              1
Emergency Response Team (ERT)     1
Hazardous Materials               1
Building/Use                      1
AHV Inspection Unit               1
Name: complaint_type, dtype: int64

In [17]:
df[(df['location_type'].isnull()) & (df['complaint_type'] == 'Water System')]

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type
20,58121385,2023-07-05T22:20:00.000,2023-07-07T10:33:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,ONLINE,40.841752298115495,-73.9143883173933,NaN
22,58117034,2023-07-05T22:20:00.000,2023-07-05T22:20:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11207,Closed,04 BROOKLYN,BROOKLYN,ONLINE,40.688931453698274,-73.90504343933692,NaN
23,58123160,2023-07-05T22:20:00.000,2023-07-05T22:20:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10040,Closed,12 MANHATTAN,MANHATTAN,PHONE,40.85482728192759,-73.92943094675587,NaN
24,58114013,2023-07-05T22:20:00.000,2023-07-06T00:30:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10029,Closed,11 MANHATTAN,MANHATTAN,ONLINE,40.79125760216967,-73.94600241145547,NaN
26,58122944,2023-07-05T22:20:00.000,2023-07-09T11:15:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10462,Closed,11 BRONX,BRONX,PHONE,NaN,NaN,NaN
85,58119900,2023-07-05T22:14:00.000,2023-07-08T10:20:00.000,DEP,Department of Environmental Protection,Water System,Dirty Water (WE),10467,Closed,11 BRONX,BRONX,PHONE,40.86700103237368,-73.87045265395106,NaN
151,58114018,2023-07-05T22:08:00.000,2023-07-07T13:07:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10453,Closed,05 BRONX,BRONX,PHONE,40.84540276794456,-73.91077651116483,NaN
152,58114512,2023-07-05T22:08:00.000,2023-07-06T12:18:00.000,DEP,Department of Environmental Protection,Water System,No Water (WNW),10463,Closed,08 BRONX,BRONX,ONLINE,40.888712226428794,-73.91559729951,NaN
187,58120127,2023-07-05T22:05:00.000,2023-07-11T12:04:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10451,Closed,04 BRONX,BRONX,MOBILE,40.82288811888282,-73.92668272086536,NaN
209,58117141,2023-07-05T22:02:00.000,2023-07-11T18:35:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,MOBILE,40.837488438419626,-73.92426699698568,NaN
233,58123074,2023-07-05T21:59:00.000,2023-07-11T20:50:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10457,Closed,04 BRONX,BRONX,PHONE,40.84268250588943,-73.90697803268651,NaN
234,58121920,2023-07-05T21:59:00.000,2023-07-07T13:10:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Locking Device Request (Use Comments) ...,10453,Closed,05 BRONX,BRONX,PHONE,40.84540276794456,-73.91077651116483,NaN
235,58121415,2023-07-05T21:59:00.000,2023-07-05T21:59:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10040,Closed,12 MANHATTAN,MANHATTAN,PHONE,40.85741279181908,-73.92943181839,NaN
253,58112332,2023-07-05T21:56:00.000,2023-07-07T13:08:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10453,Closed,05 BRONX,BRONX,PHONE,40.84540276794456,-73.91077651116483,NaN
254,58112094,2023-07-05T21:56:00.000,2023-07-06T13:10:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running (WC3),10040,Closed,12 MANHATTAN,MANHATTAN,MOBILE,40.85844745053305,-73.92927888866892,NaN
256,58121553,2023-07-05T21:56:00.000,2023-07-12T09:04:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running (WC3),10452,Closed,04 BRONX,BRONX,ONLINE,40.845138089074176,-73.9244896046163,NaN
336,58120031,2023-07-05T21:47:00.000,2023-07-07T13:09:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10453,Closed,05 BRONX,BRONX,PHONE,40.84540276794456,-73.91077651116483,NaN
337,58122968,2023-07-05T21:47:00.000,2023-07-05T22:04:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10459,Closed,02 BRONX,BRONX,PHONE,40.81748793864393,-73.89635181430359,NaN
339,58121521,2023-07-05T21:47:00.000,2023-07-06T21:10:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Locking Device Request (Use Comments) ...,10459,Closed,02 BRONX,BRONX,PHONE,40.81748793864393,-73.89635181430359,NaN
341,58121416,2023-07-05T21:47:00.000,2023-07-05T21:47:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10040,Closed,12 MANHATTAN,MANHATTAN,ONLINE,40.86095711672414,-73.92650337566882,NaN
342,58118662,2023-07-05T21:47:00.000,2023-07-05T21:47:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10033,Closed,12 MANHATTAN,MANHATTAN,ONLINE,40.84914379115813,-73.93546964261812,NaN
376,58118537,2023-07-05T21:44:00.000,2023-07-05T22:12:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,PHONE,40.83164040026259,-73.93010959913208,NaN
377,58112256,2023-07-05T21:44:00.000,2023-07-06T09:20:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11208,Closed,05 BROOKLYN,BROOKLYN,PHONE,40.674122793983194,-73.88080250056282,NaN
405,58112148,2023-07-05T21:41:00.000,2023-07-07T07:45:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running (WC3),10457,Closed,04 BRONX,BRONX,PHONE,NaN,NaN,NaN
440,58114091,2023-07-05T21:38:00.000,2023-07-05T22:07:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10457,Closed,06 BRONX,BRONX,MOBILE,40.85135677239503,-73.8953230790979,NaN
465,58120128,2023-07-05T21:35:00.000,2023-08-01T09:10:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10472,Closed,09 BRONX,BRONX,ONLINE,40.831706041426315,-73.85811228962753,NaN
486,58113966,2023-07-05T21:32:00.000,2023-07-14T12:24:00.000,DEP,Department of Environmental Protection,Water System,Dirty Water (WE),10463,Closed,08 BRONX,BRONX,ONLINE,40.87505972622432,-73.90450281860619,NaN
487,58117130,2023-07-05T21:32:00.000,2023-07-05T22:03:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10459,Closed,02 BRONX,BRONX,ONLINE,40.81755100866496,-73.89628668522636,NaN
518,58117142,2023-07-05T21:29:00.000,2023-07-07T18:30:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10463,Closed,08 BRONX,BRONX,MOBILE,40.888712226428794,-73.91559729951,NaN
539,58121560,2023-07-05T21:26:00.000,2023-07-05T21:26:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10040,Closed,12 MANHATTAN,MANHATTAN,ONLINE,40.8566561819841,-73.93096535898677,NaN
574,58115699,2023-07-05T21:23:00.000,2023-07-05T21:28:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10468,Closed,05 BRONX,BRONX,PHONE,40.86026614116041,-73.90163194510812,NaN
592,58115557,2023-07-05T21:20:00.000,2023-07-11T12:06:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running (WC3),10452,Closed,04 BRONX,BRONX,MOBILE,40.841787963205775,-73.91436658665333,NaN
593,58112180,2023-07-05T21:20:00.000,2023-07-05T22:10:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,PHONE,40.8424645106054,-73.92413483587168,NaN
595,58113912,2023-07-05T21:20:00.000,2023-07-07T14:10:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running (WC3),11211,Closed,01 BROOKLYN,BROOKLYN,MOBILE,40.70796906377863,-73.95428636079205,NaN
621,58115650,2023-07-05T21:17:00.000,2023-07-10T09:00:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Defective (WC2),11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.710726090080975,-73.95764261754552,NaN
645,58117046,2023-07-05T21:14:00.000,2023-07-06T22:50:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,MOBILE,40.83582525592861,-73.92443873957221,NaN
670,58121928,2023-07-05T21:11:00.000,2023-07-06T09:00:00.000,DEP,Department of Environmental Protection,Water System,No Water (WNW),10463,Closed,08 BRONX,BRONX,PHONE,40.888712226428794,-73.91559729951,NaN
690,58115571,2023-07-05T21:08:00.000,2023-07-05T21:15:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10455,Closed,01 BRONX,BRONX,PHONE,40.80906017422442,-73.90753797955016,NaN
752,58113026,2023-07-05T20:59:00.000,2023-07-05T22:15:00.000,DEP,Department of Environmental Protection,Water System,No Water (WNW),10309,Closed,03 STATEN ISLAND,STATEN ISLAND,PHONE,40.53373397425343,-74.23519993767404,NaN
777,58119950,2023-07-05T20:56:00.000,2023-07-11T17:57:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10468,Closed,05 BRONX,BRONX,PHONE,40.85992686247838,-73.89968027854793,NaN
778,58112383,2023-07-05T20:56:00.000,2023-07-05T21:01:00.000,DEP,Department of Environmental Protection,Water System,Possible Water Main Break (Use Comments) (WA1),11413,Closed,12 QUEENS,QUEENS,PHONE,NaN,NaN,NaN
795,58118513,2023-07-05T20:53:00.000,2023-07-05T21:13:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10456,Closed,04 BRONX,BRONX,ONLINE,40.83767382859059,-73.91461762857192,NaN
798,58115572,2023-07-05T20:53:00.000,2023-07-05T21:12:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10453,Closed,05 BRONX,BRONX,PHONE,40.84540276794456,-73.91077651116483,NaN
799,58117240,2023-07-05T20:53:00.000,2023-07-06T01:50:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11211,Closed,01 BROOKLYN,BROOKLYN,MOBILE,40.70767226334634,-73.95337402682746,NaN
813,58112171,2023-07-05T20:50:00.000,2023-07-06T06:30:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10033,Closed,12 MANHATTAN,MANHATTAN,ONLINE,40.849840663730916,-73.93496654033319,NaN
814,58121368,2023-07-05T20:50:00.000,2023-07-05T20:50:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10040,Closed,12 MANHATTAN,MANHATTAN,PHONE,40.85504442833419,-73.9299476413543,NaN
834,58112231,2023-07-05T20:47:00.000,2023-07-06T00:55:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10040,Closed,12 MANHATTAN,MANHATTAN,PHONE,40.85642300342694,-73.9311680373762,NaN
851,58117095,2023-07-05T20:44:00.000,2023-07-05T22:15:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10009,Closed,03 MANHATTAN,MANHATTAN,MOBILE,40.72842720439448,-73.97779281844218,NaN
868,58115718,2023-07-05T20:41:00.000,2023-07-06T11:00:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11368,Closed,03 QUEENS,QUEENS,PHONE,40.75073396300653,-73.86291175317541,NaN
903,58112232,2023-07-05T20:35:00.000,2023-07-05T21:19:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10459,Closed,02 BRONX,BRONX,ONLINE,40.81755100866496,-73.89628668522636,NaN
904,58121369,2023-07-05T20:35:00.000,2023-07-05T20:35:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10031,Closed,09 MANHATTAN,MANHATTAN,ONLINE,40.8297892081527,-73.94277320486097,NaN
905,58112295,2023-07-05T20:35:00.000,2023-07-11T20:35:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10457,Closed,04 BRONX,BRONX,PHONE,40.84306113235555,-73.90680040695833,NaN
943,58122919,2023-07-05T20:29:00.000,2023-07-05T20:29:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10032,Closed,12 MANHATTAN,MANHATTAN,ONLINE,40.83882344002816,-73.94563493239124,NaN
944,58119934,2023-07-05T20:29:00.000,2023-07-06T00:35:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Locking Device Request (Use Comments) ...,10040,Closed,12 MANHATTAN,MANHATTAN,ONLINE,40.85694143782184,-73.93064333117792,NaN
965,58120032,2023-07-05T20:26:00.000,2023-07-06T08:50:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11432,Closed,12 QUEENS,QUEENS,PHONE,40.70624590976947,-73.80031350983778,NaN
966,58118538,2023-07-05T20:26:00.000,2023-07-05T20:26:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10031,Closed,09 MANHATTAN,MANHATTAN,ONLINE,40.827090867999,-73.94796428323792,NaN
982,58114066,2023-07-05T20:23:00.000,2023-07-05T21:00:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11220,Closed,07 BROOKLYN,BROOKLYN,PHONE,40.643425901464816,-74.01206416378167,NaN

In [18]:
# Assigning the value of location_type2 field to 'Water System' for rows that satisfy the following conditions:
# location_type value is null AND complaint type value is 'Water System'
df.loc[(df['location_type'].isnull()) & (df['complaint_type'] == 'Water System'), 'location_type2'] = 'Water System'

In [19]:
# For rows with null location type values, outputs unique descriptor type values
df[df['location_type'].isnull()]['descriptor'].unique()

array(['Building Permit - None',
       'Elevator - Single Device On Property/No Alternate Service',
       'Lead Kit Request (Residential) (L10)',
       'Hydrant Running Full (WA4)', 'Noise, Barking Dog (NR5)',
       'Controller', 'Air: Odor/Fumes, Vehicle Idling (AD3)',
       'Noise: Construction Before/After Hours (NM1)', 'Dirty Water (WE)',
       'Illegal Use Of A Hydrant (CIN)', 'Underground', 'No Water (WNW)',
       'Failure to Comply with Vacate Order',
       'Sidewalk Shed/Pipe Scafford - Inadequate Defective/None',
       'Street Light Out',
       'Hydrant Locking Device Request (Use Comments) (WC5)', 'Pothole',
       'Fence - None/Inadequate', 'Hydrant Running (WC3)',
       'Catch Basin Clogged/Flooding (Use Comments) (SC)',
       'Noise: Alarms (NR3)', 'After Hours Work - Illegal',
       'Building Shaking/Vibrating/Structural Stability',
       'Traffic Signal Light',
       'Egress - Doors Locked/Blocked/Improper/No Secondary Means',
       'Chemical Odor (HD1)', 'Hydrant Defective (WC2)',
       'Illegal Conversion Of Residential Building/Space',
       'Possible Water Main Break (Use Comments) (WA1)',
       'After Hours Work - With An AHV Permit',
       'Elevator - Multiple Devices On Property', 'Debris - Excessive',
       'Veh Signal Lamp'], dtype=object)

In [20]:
# For rows with null location type values, outputs unique descriptor type values and number of associated rows
df[df['location_type'].isnull()]['descriptor'].value_counts()

Hydrant Running Full (WA4)                                   42
Air: Odor/Fumes, Vehicle Idling (AD3)                        18
Street Light Out                                              8
Controller                                                    8
Underground                                                   7
Hydrant Running (WC3)                                         5
Pothole                                                       3
Noise: Alarms (NR3)                                           3
Catch Basin Clogged/Flooding (Use Comments) (SC)              3
Noise: Construction Before/After Hours (NM1)                  3
Illegal Use Of A Hydrant (CIN)                                3
No Water (WNW)                                                3
Hydrant Locking Device Request (Use Comments) (WC5)           3
Elevator - Single Device On Property/No Alternate Service     2
Failure to Comply with Vacate Order                           2
Dirty Water (WE)                                              2
After Hours Work - With An AHV Permit                         1
Egress - Doors Locked/Blocked/Improper/No Secondary Means     1
Possible Water Main Break (Use Comments) (WA1)                1
Elevator - Multiple Devices On Property                       1
Debris - Excessive                                            1
Illegal Conversion Of Residential Building/Space              1
Hydrant Defective (WC2)                                       1
Chemical Odor (HD1)                                           1
Building Permit - None                                        1
Traffic Signal Light                                          1
Building Shaking/Vibrating/Structural Stability               1
After Hours Work - Illegal                                    1
Fence - None/Inadequate                                       1
Sidewalk Shed/Pipe Scafford - Inadequate Defective/None       1
Noise, Barking Dog (NR5)                                      1
Lead Kit Request (Residential) (L10)                          1
Veh Signal Lamp                                               1
Name: descriptor, dtype: int64

In [21]:
# Outputs all unique values for location_type field
df['location_type'].unique()

array([nan, 'Residential Building/House', 'Street/Sidewalk', 'Park',
       'Store/Commercial', 'RESIDENTIAL BUILDING', 'Street', 'Taxi',
       'Sidewalk', '3+ Family Apt. Building', 'Park/Playground',
       'Commercial Building', '3+ Family Apartment Building',
       'Club/Bar/Restaurant', 'Gutter', 'Alley', 'Other (Explain Below)',
       'Business', 'Street/Curbside', '1-2 Family Dwelling', 'Vacant Lot'],
      dtype=object)

In [22]:
# Outputs number of records for each unique location type value
df['location_type'].value_counts()

Street/Sidewalk                 442
RESIDENTIAL BUILDING            147
Residential Building/House      123
Street                           36
Sidewalk                         30
Park/Playground                  26
Park                             16
3+ Family Apt. Building          15
Business                          5
Club/Bar/Restaurant               4
Commercial Building               4
Store/Commercial                  4
Other (Explain Below)             3
1-2 Family Dwelling               3
3+ Family Apartment Building      2
Taxi                              1
Gutter                            1
Alley                             1
Street/Curbside                   1
Vacant Lot                        1
Name: location_type, dtype: int64

In [23]:
# Creating a new location type field named location_type2 to have fewer unique values for location type
# Value for location_type2 field will be based on conditions for the location_type field in each row
def new_loc (location_type):
    if (location_type == 'RESIDENTIAL BUILDING') | (location_type == 'Residential Building/House') | (location_type == '3+ Family Apt. Building') | (location_type == '3+ Family Apartment Building') |(location_type == '1-2 Family Dwelling'):
        return 'Residential'
    elif (location_type == 'Street/Sidewalk') | (location_type == 'Street') | (location_type == 'Sidewalk') | (location_type == 'Street/Curbside') | (location_type == 'Gutter') | (location_type == 'Alley'):
        return 'Street/Sidewalk'
    elif (location_type == 'Business') | (location_type == 'Club/Bar/Restaurant') | (location_type == 'Commercial Building') | (location_type == 'Store/Commercial'):
        return 'Business/Commercial'
    elif (location_type == 'Subway'):
        return 'Subway'
    elif (location_type == 'Taxi'):
        return 'Taxi'
    elif (location_type == 'Park/Playground') | (location_type == 'Park'):
        return 'Park'
    else:
        return 'Other/Unknown'

df['location_type2'] = df['location_type'].map(new_loc)

#new_loc = {
#     'Street/Sidewalk': ["Street/Sidewalk", "Street", "Sidewalk", "Gutter", "Alley","Street/Curbside"],
#     'Residential':['RESIDENTIAL BUILDING','Residential Building/House','3+ Family Apt. Building', '3+ Family Apartment Building', '1-2 Family Dwelling'],
#    'Business/Commercial':['Business','Club/Bar/Restaurant','Commercial Building','Store/Commercial'],
 #    'Subway':['Subway'],
 #    'Taxi':['Taxi'],
 #    'Park':['Park/Playground','Park'],
 #    'Other/Unknown':['Other (Explain Below)','Gutter','Alley','Vacant Lot']
#}

#df['location_type2'] = df['location_type'].map(new_loc)

In [24]:
df['location_type2'].value_counts()

Street/Sidewalk        511
Residential            290
Other/Unknown          136
Park                    42
Business/Commercial     17
Taxi                     1
Name: location_type2, dtype: int64

In [25]:
df[df['location_type2']=='Other/Unknown']

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type,location_type2
0,58116814,2023-07-05T22:22:03.000,2023-08-09T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,UNKNOWN,40.53648118922242,-74.15657605064793,NaN,Other/Unknown
1,58112935,2023-07-05T22:22:03.000,2023-08-03T00:00:00.000,DOB,Department of Buildings,Elevator,Elevator - Single Device On Property/No Altern...,10459,Closed,02 BRONX,BRONX,UNKNOWN,40.82319312657684,-73.88927925606889,NaN,Other/Unknown
19,58117014,2023-07-05T22:20:00.000,2023-07-06T09:29:00.000,DEP,Department of Environmental Protection,Lead,Lead Kit Request (Residential) (L10),10280,Closed,01 MANHATTAN,MANHATTAN,ONLINE,40.70811402884461,-74.017630483332,NaN,Other/Unknown
20,58121385,2023-07-05T22:20:00.000,2023-07-07T10:33:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,ONLINE,40.841752298115495,-73.9143883173933,NaN,Other/Unknown
21,58121315,2023-07-05T22:20:00.000,2023-07-06T08:51:00.000,DEP,Department of Environmental Protection,Noise,"Noise, Barking Dog (NR5)",11208,Closed,05 BROOKLYN,BROOKLYN,ONLINE,40.68773380465783,-73.8728021572523,NaN,Other/Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,58122411,2023-07-05T20:23:36.000,2023-08-23T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Debris - Excessive,11211,Closed,01 BROOKLYN,BROOKLYN,UNKNOWN,40.71463773373357,-73.93993577498533,NaN,Other/Unknown
981,58117016,2023-07-05T20:23:00.000,2023-07-06T20:45:00.000,DEP,Department of Environmental Protection,Noise,Noise: Alarms (NR3),11230,Closed,14 BROOKLYN,BROOKLYN,PHONE,40.63298747798288,-73.97212850230288,NaN,Other/Unknown
982,58114066,2023-07-05T20:23:00.000,2023-07-05T21:00:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11220,Closed,07 BROOKLYN,BROOKLYN,PHONE,40.643425901464816,-74.01206416378167,NaN,Other/Unknown
992,58107939,2023-07-05T20:21:00.000,2023-07-06T02:25:00.000,DOT,Department of Transportation,Traffic Signal Condition,Veh Signal Lamp,11213,Closed,08 BROOKLYN,BROOKLYN,UNKNOWN,40.67325789139592,-73.93069735829563,NaN,Other/Unknown
993,58106580,2023-07-05T20:21:00.000,2023-07-07T09:50:00.000,DOT,Department of Transportation,Traffic Signal Condition,Controller,11373,Closed,04 QUEENS,QUEENS,UNKNOWN,40.73888938191339,-73.86676119844235,NaN,Other/Unknown

In [26]:
df[df['location_type2']=='Other/Unknown']['complaint_type'].value_counts()

Water System                     57
Air Quality                      18
Traffic Signal Condition         16
Street Light Condition            9
General Construction/Plumbing     8
Noise                             7
Rodent                            4
Elevator                          3
Water Conservation                3
Street Condition                  3
Sewer                             3
Lead                              1
Emergency Response Team (ERT)     1
Hazardous Materials               1
Building/Use                      1
AHV Inspection Unit               1
Name: complaint_type, dtype: int64

In [27]:
# Changing location_type 2 values to some rows originally marked as 'Other/Unknown'
df.loc[(df['location_type2'] =='Other/Unknown') & (df['complaint_type'] == 'Traffic Signal Condition'), 'location_type2'] = 'Street/Sidewalk'
df.loc[(df['location_type2'] =='Other/Unknown') & (df['complaint_type'] == 'Street Light Condition'), 'location_type2'] = 'Street/Sidewalk'
df.loc[(df['location_type2'] =='Other/Unknown') & (df['complaint_type'] == 'Sewer'), 'location_type2'] = 'Sewer System'

In [28]:
df['location_type2'].value_counts()

Street/Sidewalk        536
Residential            290
Other/Unknown          108
Park                    42
Business/Commercial     17
Sewer System             3
Taxi                     1
Name: location_type2, dtype: int64

In [29]:
df[df['location_type2']=='Other/Unknown']

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type,location_type2
0,58116814,2023-07-05T22:22:03.000,2023-08-09T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,UNKNOWN,40.53648118922242,-74.15657605064793,NaN,Other/Unknown
1,58112935,2023-07-05T22:22:03.000,2023-08-03T00:00:00.000,DOB,Department of Buildings,Elevator,Elevator - Single Device On Property/No Altern...,10459,Closed,02 BRONX,BRONX,UNKNOWN,40.82319312657684,-73.88927925606889,NaN,Other/Unknown
19,58117014,2023-07-05T22:20:00.000,2023-07-06T09:29:00.000,DEP,Department of Environmental Protection,Lead,Lead Kit Request (Residential) (L10),10280,Closed,01 MANHATTAN,MANHATTAN,ONLINE,40.70811402884461,-74.017630483332,NaN,Other/Unknown
20,58121385,2023-07-05T22:20:00.000,2023-07-07T10:33:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10452,Closed,04 BRONX,BRONX,ONLINE,40.841752298115495,-73.9143883173933,NaN,Other/Unknown
21,58121315,2023-07-05T22:20:00.000,2023-07-06T08:51:00.000,DEP,Department of Environmental Protection,Noise,"Noise, Barking Dog (NR5)",11208,Closed,05 BROOKLYN,BROOKLYN,ONLINE,40.68773380465783,-73.8728021572523,NaN,Other/Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,58120032,2023-07-05T20:26:00.000,2023-07-06T08:50:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11432,Closed,12 QUEENS,QUEENS,PHONE,40.70624590976947,-73.80031350983778,NaN,Other/Unknown
966,58118538,2023-07-05T20:26:00.000,2023-07-05T20:26:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10031,Closed,09 MANHATTAN,MANHATTAN,ONLINE,40.827090867999,-73.94796428323792,NaN,Other/Unknown
978,58122411,2023-07-05T20:23:36.000,2023-08-23T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Debris - Excessive,11211,Closed,01 BROOKLYN,BROOKLYN,UNKNOWN,40.71463773373357,-73.93993577498533,NaN,Other/Unknown
981,58117016,2023-07-05T20:23:00.000,2023-07-06T20:45:00.000,DEP,Department of Environmental Protection,Noise,Noise: Alarms (NR3),11230,Closed,14 BROOKLYN,BROOKLYN,PHONE,40.63298747798288,-73.97212850230288,NaN,Other/Unknown
982,58114066,2023-07-05T20:23:00.000,2023-07-05T21:00:00.000,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),11220,Closed,07 BROOKLYN,BROOKLYN,PHONE,40.643425901464816,-74.01206416378167,NaN,Other/Unknown

In [30]:
df[df['location_type2']=='Other/Unknown']['descriptor'].value_counts()

Hydrant Running Full (WA4)                                   42
Air: Odor/Fumes, Vehicle Idling (AD3)                        18
Hydrant Running (WC3)                                         5
Noise: Construction Before/After Hours (NM1)                  3
Illegal Use Of A Hydrant (CIN)                                3
No Water (WNW)                                                3
Noise: Alarms (NR3)                                           3
Rat Sighting                                                  3
Hydrant Locking Device Request (Use Comments) (WC5)           3
Pothole                                                       3
Failure to Comply with Vacate Order                           2
Dirty Water (WE)                                              2
Elevator - Single Device On Property/No Alternate Service     2
Illegal Conversion Of Residential Building/Space              1
Possible Water Main Break (Use Comments) (WA1)                1
Building Permit - None                                        1
Condition Attracting Rodents                                  1
Chemical Odor (HD1)                                           1
After Hours Work - With An AHV Permit                         1
Elevator - Multiple Devices On Property                       1
Hydrant Defective (WC2)                                       1
Fence - None/Inadequate                                       1
Egress - Doors Locked/Blocked/Improper/No Secondary Means     1
Building Shaking/Vibrating/Structural Stability               1
After Hours Work - Illegal                                    1
Sidewalk Shed/Pipe Scafford - Inadequate Defective/None       1
Noise, Barking Dog (NR5)                                      1
Lead Kit Request (Residential) (L10)                          1
Debris - Excessive                                            1
Name: descriptor, dtype: int64

In [31]:
df.loc[(df['location_type2'] =='Other/Unknown') & (df['descriptor'] == 'Pothole'), 'location_type2'] = 'Street/Sidewalk'
df.loc[(df['location_type2'] =='Other/Unknown') & (df['descriptor'] == 'Lead Kit Request (Residential) (L10)'), 'location_type2'] = 'Residential'
df.loc[(df['location_type2'] =='Other/Unknown') & (df['descriptor'] == 'Air: Odor/Fumes, Vehicle Idling (AD3)'), 'location_type2'] = 'Street/Sidewalk'

In [32]:
df[df['location_type2']=='Other/Unknown']['descriptor'].value_counts()

Hydrant Running Full (WA4)                                   42
Hydrant Running (WC3)                                         5
Rat Sighting                                                  3
Noise: Construction Before/After Hours (NM1)                  3
Illegal Use Of A Hydrant (CIN)                                3
No Water (WNW)                                                3
Hydrant Locking Device Request (Use Comments) (WC5)           3
Noise: Alarms (NR3)                                           3
Elevator - Single Device On Property/No Alternate Service     2
Dirty Water (WE)                                              2
Failure to Comply with Vacate Order                           2
Illegal Conversion Of Residential Building/Space              1
Possible Water Main Break (Use Comments) (WA1)                1
After Hours Work - With An AHV Permit                         1
Condition Attracting Rodents                                  1
Chemical Odor (HD1)                                           1
Elevator - Multiple Devices On Property                       1
Hydrant Defective (WC2)                                       1
Building Permit - None                                        1
Egress - Doors Locked/Blocked/Improper/No Secondary Means     1
Building Shaking/Vibrating/Structural Stability               1
After Hours Work - Illegal                                    1
Fence - None/Inadequate                                       1
Sidewalk Shed/Pipe Scafford - Inadequate Defective/None       1
Noise, Barking Dog (NR5)                                      1
Debris - Excessive                                            1
Name: descriptor, dtype: int64

In [33]:
df['location_type2'].value_counts()

Street/Sidewalk        557
Residential            291
Other/Unknown           86
Park                    42
Business/Commercial     17
Sewer System             3
Taxi                     1
Name: location_type2, dtype: int64

In [34]:
df['agency'].value_counts()

NYPD     598
HPD      147
DEP       90
DSNY      48
DOT       40
DOHMH     28
DPR       25
DOB       14
DCWP       5
TLC        1
DHS        1
Name: agency, dtype: int64

In [35]:
df['agency_name'].value_counts()

New York City Police Department                       598
Department of Housing Preservation and Development    147
Department of Environmental Protection                 90
Department of Sanitation                               48
Department of Transportation                           40
Department of Health and Mental Hygiene                28
Department of Parks and Recreation                     25
Department of Buildings                                14
Department of Consumer and Worker Protection            5
Taxi and Limousine Commission                           1
Department of Homeless Services                         1
Name: agency_name, dtype: int64

In [36]:
df['created_date2'] = pd.to_datetime(df['created_date'], format='%Y-%m-%dT%H:%M:%S.%f')

In [37]:
df['closed_date2'] = pd.to_datetime(df['closed_date'], format='%Y-%m-%dT%H:%M:%S.%f')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_key              997 non-null    object
 1   created_date            997 non-null    object
 2   closed_date             997 non-null    object
 3   agency                  997 non-null    object
 4   agency_name             997 non-null    object
 5   complaint_type          997 non-null    object
 6   descriptor              997 non-null    object
 7   incident_zip            997 non-null    object
 8   status                  997 non-null    object
 9   community_board         997 non-null    object
 10  borough                 997 non-null    object
 11  open_data_channel_type  997 non-null    object
 12  latitude                986 non-null    object
 13  longitude               986 non-null    object
 14  location_type           865 non-null    object
 15  location_type2          997 non-null    object
 16  created_date2           997 non-null    datetime64[ns]
 17  closed_date2            997 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(16)
memory usage: 140.3+ KB

In [39]:
df.head(10)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type,location_type2,created_date2,closed_date2
0,58116814,2023-07-05T22:22:03.000,2023-08-09T00:00:00.000,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,UNKNOWN,40.53648118922242,-74.15657605064793,NaN,Other/Unknown,2023-07-05 22:22:03,2023-08-09 00:00:00
1,58112935,2023-07-05T22:22:03.000,2023-08-03T00:00:00.000,DOB,Department of Buildings,Elevator,Elevator - Single Device On Property/No Altern...,10459,Closed,02 BRONX,BRONX,UNKNOWN,40.82319312657684,-73.88927925606889,NaN,Other/Unknown,2023-07-05 22:22:03,2023-08-03 00:00:00
2,58102542,2023-07-05T22:21:45.000,2023-07-05T22:38:37.000,NYPD,New York City Police Department,Illegal Fireworks,N/A,11213,Closed,09 BROOKLYN,BROOKLYN,ONLINE,40.664271427215475,-73.93059495473237,Residential Building/House,Residential,2023-07-05 22:21:45,2023-07-05 22:38:37
3,58101494,2023-07-05T22:21:41.000,2023-07-05T22:50:13.000,NYPD,New York City Police Department,Blocked Driveway,No Access,11369,Closed,03 QUEENS,QUEENS,PHONE,40.75865400041392,-73.876305234797,Street/Sidewalk,Street/Sidewalk,2023-07-05 22:21:41,2023-07-05 22:50:13
4,58104528,2023-07-05T22:21:38.000,2023-07-05T22:50:01.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,10302,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63333427323517,-74.13502403610045,Residential Building/House,Residential,2023-07-05 22:21:38,2023-07-05 22:50:01
5,58105506,2023-07-05T22:21:34.000,2023-07-06T00:32:37.000,NYPD,New York City Police Department,Illegal Fireworks,N/A,10310,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63776682754764,-74.11509349235297,Street/Sidewalk,Street/Sidewalk,2023-07-05 22:21:34,2023-07-06 00:32:37
6,58104527,2023-07-05T22:21:12.000,2023-07-05T22:55:11.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.71888381029733,-73.95142536226368,Residential Building/House,Residential,2023-07-05 22:21:12,2023-07-05 22:55:11
7,58103805,2023-07-05T22:21:02.000,2023-07-05T23:14:51.000,NYPD,New York City Police Department,Blocked Driveway,Partial Access,11210,Closed,14 BROOKLYN,BROOKLYN,ONLINE,40.61691917007343,-73.94765626630915,Street/Sidewalk,Street/Sidewalk,2023-07-05 22:21:02,2023-07-05 23:14:51
8,58108576,2023-07-05T22:21:02.000,2023-07-05T22:59:13.000,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,10467,Closed,07 BRONX,BRONX,MOBILE,40.882211991020355,-73.88317784449366,Street/Sidewalk,Street/Sidewalk,2023-07-05 22:21:02,2023-07-05 22:59:13
9,58104251,2023-07-05T22:21:02.000,2023-07-05T22:23:20.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,11209,Closed,10 BROOKLYN,BROOKLYN,ONLINE,40.61814816576145,-74.03164022879972,Residential Building/House,Residential,2023-07-05 22:21:02,2023-07-05 22:23:20

In [40]:
df['created_date'] = df['created_date2']
df['closed_date'] = df['closed_date2']
df = df.drop(columns=['created_date2','closed_date2'])

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_key              997 non-null    object
 1   created_date            997 non-null    datetime64[ns]
 2   closed_date             997 non-null    datetime64[ns]
 3   agency                  997 non-null    object
 4   agency_name             997 non-null    object
 5   complaint_type          997 non-null    object
 6   descriptor              997 non-null    object
 7   incident_zip            997 non-null    object
 8   status                  997 non-null    object
 9   community_board         997 non-null    object
 10  borough                 997 non-null    object
 11  open_data_channel_type  997 non-null    object
 12  latitude                986 non-null    object
 13  longitude               986 non-null    object
 14  location_type           865 non-null    object
 15  location_type2          997 non-null    object
dtypes: datetime64[ns](2), object(14)
memory usage: 124.8+ KB

In [42]:
df = df.drop(columns = ['location_type'])
df = df.rename(columns = {'location_type2':'location_type'})

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_key              997 non-null    object
 1   created_date            997 non-null    datetime64[ns]
 2   closed_date             997 non-null    datetime64[ns]
 3   agency                  997 non-null    object
 4   agency_name             997 non-null    object
 5   complaint_type          997 non-null    object
 6   descriptor              997 non-null    object
 7   incident_zip            997 non-null    object
 8   status                  997 non-null    object
 9   community_board         997 non-null    object
 10  borough                 997 non-null    object
 11  open_data_channel_type  997 non-null    object
 12  latitude                986 non-null    object
 13  longitude               986 non-null    object
 14  location_type           997 non-null    object
dtypes: datetime64[ns](2), object(13)
memory usage: 117.0+ KB

In [44]:
df[df['latitude'].isnull()]

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type
26,58122944,2023-07-05 22:20:00,2023-07-09 11:15:00,DEP,Department of Environmental Protection,Water System,Hydrant Running Full (WA4),10462,Closed,11 BRONX,BRONX,PHONE,NaN,NaN,Other/Unknown
195,58111312,2023-07-05 22:04:03,2023-07-05 22:08:51,NYPD,New York City Police Department,Illegal Fireworks,N/A,11209,Closed,Unspecified BROOKLYN,BROOKLYN,PHONE,NaN,NaN,Street/Sidewalk
218,58107242,2023-07-05 22:01:18,2023-07-05 22:10:28,NYPD,New York City Police Department,Illegal Fireworks,N/A,11209,Closed,Unspecified BROOKLYN,BROOKLYN,ONLINE,NaN,NaN,Street/Sidewalk
223,58106191,2023-07-05 22:00:41,2023-07-05 22:24:38,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,10031,Closed,Unspecified MANHATTAN,MANHATTAN,ONLINE,NaN,NaN,Street/Sidewalk
240,58102651,2023-07-05 21:58:17,2023-07-06 22:30:00,DOT,Department of Transportation,Street Condition,Pothole,11234,Closed,18 BROOKLYN,BROOKLYN,UNKNOWN,NaN,NaN,Street/Sidewalk
404,58102655,2023-07-05 21:41:02,2023-07-05 22:25:37,NYPD,New York City Police Department,Abandoned Vehicle,With License Plate,11234,Closed,Unspecified BROOKLYN,BROOKLYN,PHONE,NaN,NaN,Street/Sidewalk
405,58112148,2023-07-05 21:41:00,2023-07-07 07:45:00,DEP,Department of Environmental Protection,Water System,Hydrant Running (WC3),10457,Closed,04 BRONX,BRONX,PHONE,NaN,NaN,Other/Unknown
461,58105133,2023-07-05 21:35:57,2023-07-05 22:25:03,NYPD,New York City Police Department,Abandoned Vehicle,With License Plate,11234,Closed,Unspecified BROOKLYN,BROOKLYN,PHONE,NaN,NaN,Street/Sidewalk
624,58111169,2023-07-05 21:16:46,2023-07-05 21:17:23,NYPD,New York City Police Department,Illegal Fireworks,N/A,11209,Closed,Unspecified BROOKLYN,BROOKLYN,PHONE,NaN,NaN,Street/Sidewalk
778,58112383,2023-07-05 20:56:00,2023-07-05 21:01:00,DEP,Department of Environmental Protection,Water System,Possible Water Main Break (Use Comments) (WA1),11413,Closed,12 QUEENS,QUEENS,PHONE,NaN,NaN,Other/Unknown
800,58107834,2023-07-05 20:52:49,2023-07-06 08:00:00,DOT,Department of Transportation,Street Condition,Pothole,11104,Closed,02 QUEENS,QUEENS,UNKNOWN,NaN,NaN,Street/Sidewalk

In [45]:
df.head(10)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type
0,58116814,2023-07-05 22:22:03,2023-08-09 00:00:00,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,UNKNOWN,40.53648118922242,-74.15657605064793,Other/Unknown
1,58112935,2023-07-05 22:22:03,2023-08-03 00:00:00,DOB,Department of Buildings,Elevator,Elevator - Single Device On Property/No Altern...,10459,Closed,02 BRONX,BRONX,UNKNOWN,40.82319312657684,-73.88927925606889,Other/Unknown
2,58102542,2023-07-05 22:21:45,2023-07-05 22:38:37,NYPD,New York City Police Department,Illegal Fireworks,N/A,11213,Closed,09 BROOKLYN,BROOKLYN,ONLINE,40.664271427215475,-73.93059495473237,Residential
3,58101494,2023-07-05 22:21:41,2023-07-05 22:50:13,NYPD,New York City Police Department,Blocked Driveway,No Access,11369,Closed,03 QUEENS,QUEENS,PHONE,40.75865400041392,-73.876305234797,Street/Sidewalk
4,58104528,2023-07-05 22:21:38,2023-07-05 22:50:01,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,10302,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63333427323517,-74.13502403610045,Residential
5,58105506,2023-07-05 22:21:34,2023-07-06 00:32:37,NYPD,New York City Police Department,Illegal Fireworks,N/A,10310,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63776682754764,-74.11509349235297,Street/Sidewalk
6,58104527,2023-07-05 22:21:12,2023-07-05 22:55:11,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.71888381029733,-73.95142536226368,Residential
7,58103805,2023-07-05 22:21:02,2023-07-05 23:14:51,NYPD,New York City Police Department,Blocked Driveway,Partial Access,11210,Closed,14 BROOKLYN,BROOKLYN,ONLINE,40.61691917007343,-73.94765626630915,Street/Sidewalk
8,58108576,2023-07-05 22:21:02,2023-07-05 22:59:13,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,10467,Closed,07 BRONX,BRONX,MOBILE,40.882211991020355,-73.88317784449366,Street/Sidewalk
9,58104251,2023-07-05 22:21:02,2023-07-05 22:23:20,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,11209,Closed,10 BROOKLYN,BROOKLYN,ONLINE,40.61814816576145,-74.03164022879972,Residential

In [46]:
df.tail(10)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type
987,58103781,2023-07-05 20:22:33,2023-07-05 20:25:45,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,11228,Closed,10 BROOKLYN,BROOKLYN,ONLINE,40.61766136207577,-74.0243783589393,Street/Sidewalk
988,58109814,2023-07-05 20:22:13,2023-07-06 01:58:29,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Music,10451,Closed,04 BRONX,BRONX,MOBILE,40.823069720490786,-73.92739430604901,Street/Sidewalk
989,58110551,2023-07-05 20:22:09,2023-07-05 20:45:23,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11433,Closed,12 QUEENS,QUEENS,ONLINE,40.695972973618375,-73.79450216305685,Residential
990,58104504,2023-07-05 20:21:26,2023-07-16 11:00:39,HPD,Department of Housing Preservation and Develop...,UNSANITARY CONDITION,PESTS,11416,Closed,09 QUEENS,QUEENS,ONLINE,40.68625315151093,-73.85549395422537,Residential
991,58105297,2023-07-05 20:21:21,2023-07-07 18:29:42,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.70924127809079,-73.95792851029476,Residential
992,58107939,2023-07-05 20:21:00,2023-07-06 02:25:00,DOT,Department of Transportation,Traffic Signal Condition,Veh Signal Lamp,11213,Closed,08 BROOKLYN,BROOKLYN,UNKNOWN,40.67325789139592,-73.93069735829563,Street/Sidewalk
993,58106580,2023-07-05 20:21:00,2023-07-07 09:50:00,DOT,Department of Transportation,Traffic Signal Condition,Controller,11373,Closed,04 QUEENS,QUEENS,UNKNOWN,40.73888938191339,-73.86676119844235,Street/Sidewalk
994,58108553,2023-07-05 20:20:51,2023-07-05 21:59:22,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Music,10468,Closed,08 BRONX,BRONX,ONLINE,40.8732751835183,-73.90066896231632,Street/Sidewalk
995,58105417,2023-07-05 20:20:34,2023-07-05 20:20:34,DOHMH,Department of Health and Mental Hygiene,Standing Water,Swimming Pool - Unmaintained,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,ONLINE,40.54832297298355,-74.1856166697432,Residential
996,58104686,2023-07-05 20:20:13,2023-07-05 22:01:25,NYPD,New York City Police Department,Illegal Parking,Double Parked Blocking Traffic,11207,Closed,05 BROOKLYN,BROOKLYN,MOBILE,40.68333356310445,-73.8941193737894,Street/Sidewalk

In [47]:
df['incident_duration'] = df['closed_date'] - df['created_date']

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_key              997 non-null    object
 1   created_date            997 non-null    datetime64[ns]
 2   closed_date             997 non-null    datetime64[ns]
 3   agency                  997 non-null    object
 4   agency_name             997 non-null    object
 5   complaint_type          997 non-null    object
 6   descriptor              997 non-null    object
 7   incident_zip            997 non-null    object
 8   status                  997 non-null    object
 9   community_board         997 non-null    object
 10  borough                 997 non-null    object
 11  open_data_channel_type  997 non-null    object
 12  latitude                986 non-null    object
 13  longitude               986 non-null    object
 14  location_type           997 non-null    object
 15  incident_duration       997 non-null    timedelta64[ns]
dtypes: datetime64[ns](2), object(13), timedelta64[ns](1)
memory usage: 124.8+ KB

In [49]:
df.head(10)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type,incident_duration
0,58116814,2023-07-05 22:22:03,2023-08-09 00:00:00,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,UNKNOWN,40.53648118922242,-74.15657605064793,Other/Unknown,34 days 01:37:57
1,58112935,2023-07-05 22:22:03,2023-08-03 00:00:00,DOB,Department of Buildings,Elevator,Elevator - Single Device On Property/No Altern...,10459,Closed,02 BRONX,BRONX,UNKNOWN,40.82319312657684,-73.88927925606889,Other/Unknown,28 days 01:37:57
2,58102542,2023-07-05 22:21:45,2023-07-05 22:38:37,NYPD,New York City Police Department,Illegal Fireworks,N/A,11213,Closed,09 BROOKLYN,BROOKLYN,ONLINE,40.664271427215475,-73.93059495473237,Residential,0 days 00:16:52
3,58101494,2023-07-05 22:21:41,2023-07-05 22:50:13,NYPD,New York City Police Department,Blocked Driveway,No Access,11369,Closed,03 QUEENS,QUEENS,PHONE,40.75865400041392,-73.876305234797,Street/Sidewalk,0 days 00:28:32
4,58104528,2023-07-05 22:21:38,2023-07-05 22:50:01,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,10302,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63333427323517,-74.13502403610045,Residential,0 days 00:28:23
5,58105506,2023-07-05 22:21:34,2023-07-06 00:32:37,NYPD,New York City Police Department,Illegal Fireworks,N/A,10310,Closed,01 STATEN ISLAND,STATEN ISLAND,ONLINE,40.63776682754764,-74.11509349235297,Street/Sidewalk,0 days 02:11:03
6,58104527,2023-07-05 22:21:12,2023-07-05 22:55:11,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.71888381029733,-73.95142536226368,Residential,0 days 00:33:59
7,58103805,2023-07-05 22:21:02,2023-07-05 23:14:51,NYPD,New York City Police Department,Blocked Driveway,Partial Access,11210,Closed,14 BROOKLYN,BROOKLYN,ONLINE,40.61691917007343,-73.94765626630915,Street/Sidewalk,0 days 00:53:49
8,58108576,2023-07-05 22:21:02,2023-07-05 22:59:13,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,10467,Closed,07 BRONX,BRONX,MOBILE,40.882211991020355,-73.88317784449366,Street/Sidewalk,0 days 00:38:11
9,58104251,2023-07-05 22:21:02,2023-07-05 22:23:20,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,11209,Closed,10 BROOKLYN,BROOKLYN,ONLINE,40.61814816576145,-74.03164022879972,Residential,0 days 00:02:18

In [50]:
df.tail(10)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,status,community_board,borough,open_data_channel_type,latitude,longitude,location_type,incident_duration
987,58103781,2023-07-05 20:22:33,2023-07-05 20:25:45,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,11228,Closed,10 BROOKLYN,BROOKLYN,ONLINE,40.61766136207577,-74.0243783589393,Street/Sidewalk,0 days 00:03:12
988,58109814,2023-07-05 20:22:13,2023-07-06 01:58:29,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Music,10451,Closed,04 BRONX,BRONX,MOBILE,40.823069720490786,-73.92739430604901,Street/Sidewalk,0 days 05:36:16
989,58110551,2023-07-05 20:22:09,2023-07-05 20:45:23,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11433,Closed,12 QUEENS,QUEENS,ONLINE,40.695972973618375,-73.79450216305685,Residential,0 days 00:23:14
990,58104504,2023-07-05 20:21:26,2023-07-16 11:00:39,HPD,Department of Housing Preservation and Develop...,UNSANITARY CONDITION,PESTS,11416,Closed,09 QUEENS,QUEENS,ONLINE,40.68625315151093,-73.85549395422537,Residential,10 days 14:39:13
991,58105297,2023-07-05 20:21:21,2023-07-07 18:29:42,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,11211,Closed,01 BROOKLYN,BROOKLYN,ONLINE,40.70924127809079,-73.95792851029476,Residential,1 days 22:08:21
992,58107939,2023-07-05 20:21:00,2023-07-06 02:25:00,DOT,Department of Transportation,Traffic Signal Condition,Veh Signal Lamp,11213,Closed,08 BROOKLYN,BROOKLYN,UNKNOWN,40.67325789139592,-73.93069735829563,Street/Sidewalk,0 days 06:04:00
993,58106580,2023-07-05 20:21:00,2023-07-07 09:50:00,DOT,Department of Transportation,Traffic Signal Condition,Controller,11373,Closed,04 QUEENS,QUEENS,UNKNOWN,40.73888938191339,-73.86676119844235,Street/Sidewalk,1 days 13:29:00
994,58108553,2023-07-05 20:20:51,2023-07-05 21:59:22,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Music,10468,Closed,08 BRONX,BRONX,ONLINE,40.8732751835183,-73.90066896231632,Street/Sidewalk,0 days 01:38:31
995,58105417,2023-07-05 20:20:34,2023-07-05 20:20:34,DOHMH,Department of Health and Mental Hygiene,Standing Water,Swimming Pool - Unmaintained,10312,Closed,03 STATEN ISLAND,STATEN ISLAND,ONLINE,40.54832297298355,-74.1856166697432,Residential,0 days 00:00:00
996,58104686,2023-07-05 20:20:13,2023-07-05 22:01:25,NYPD,New York City Police Department,Illegal Parking,Double Parked Blocking Traffic,11207,Closed,05 BROOKLYN,BROOKLYN,MOBILE,40.68333356310445,-73.8941193737894,Street/Sidewalk,0 days 01:41:12

In [51]:
df['complaint_type'].value_counts()

Noise - Street/Sidewalk    131
Illegal Fireworks          128
Illegal Parking            127
Noise - Residential         91
Water System                57
                          ...
Street Sign - Missing        1
Hazardous Materials          1
Outdoor Dining               1
Abandoned Bike               1
Standing Water               1
Name: complaint_type, Length: 71, dtype: int64

In [52]:
df['borough'].value_counts()

BROOKLYN         287
BRONX            228
QUEENS           225
MANHATTAN        219
STATEN ISLAND     38
Name: borough, dtype: int64

In [53]:
df[df['borough']=='BROOKLYN']['incident_zip'].value_counts()

11209    43
11226    31
11234    11
11221    10
11216    10
11224     9
11211     9
11214     9
11213     8
11232     8
11230     8
11239     8
11208     8
11228     7
11203     7
11207     7
11249     7
11235     7
11233     7
11229     6
11222     6
11220     6
11206     6
11212     6
11204     5
11223     5
11201     5
11237     4
11231     4
11238     4
11218     4
11236     3
11210     3
11215     2
11205     2
11219     1
11217     1
Name: incident_zip, dtype: int64

In [54]:
df[df['borough']=='STATEN ISLAND']['incident_zip'].value_counts()

10309    6
10312    5
10314    5
10303    4
10302    3
10305    3
10306    3
10307    3
10310    2
10304    1
10029    1
10308    1
10301    1
Name: incident_zip, dtype: int64

In [56]:
#df.to_csv('C:/Users/Public/Downloads/NYC311.csv', index=False)

In [73]:
color_scale = [(0, 'orange'), (1,'red')]

fig = px.scatter_mapbox(df, 
                        lat="latitude", 
                        lon="longitude", 
                         hover_name="borough", 
                         hover_data=["incident_zip", "complaint_type", "agency_name"],
     #                    color="incident_duration",
                        color_continuous_scale=color_scale,
     #                   size="incident_duration",
                        zoom=8, 
                        height=800,
                        width=800)

fig.update_layout(mapbox_style="open-street-map")
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_key              997 non-null    object
 1   created_date            997 non-null    datetime64[ns]
 2   closed_date             997 non-null    datetime64[ns]
 3   agency                  997 non-null    object
 4   agency_name             997 non-null    object
 5   complaint_type          997 non-null    object
 6   descriptor              997 non-null    object
 7   incident_zip            997 non-null    object
 8   status                  997 non-null    object
 9   community_board         997 non-null    object
 10  borough                 997 non-null    object
 11  open_data_channel_type  997 non-null    object
 12  latitude                986 non-null    float64
 13  longitude               986 non-null    float64
 14  location_type           997 non-null    object
 15  incident_duration       997 non-null    timedelta64[ns]
dtypes: datetime64[ns](2), float64(2), object(11), timedelta64[ns](1)
memory usage: 124.8+ KB

In [64]:
df['latitude'] = df['latitude'].astype(float)
df['longitude'] = df['longitude'].astype(float)